### ISSUE TITLE
ExtDeprecationWarning for flask.ext.cors

### ISSUE THREAD

**Issue by claman** [irskep/summertunes#7]
`ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.
  .format(x=modname), ExtDeprecationWarning`

I'm running Python 3.6 on MacOS 10.12.2

**Comment by irskep** [comment]
Oh wow, someone found this repo!

This is actually a `beet web` issue and is fortunately harmless.
